### ISSUE TITLE
Google Colab でのインストール時にエラー

### ISSUE THREAD

**Issue by lvisdd** [TadaoYamaoka/creversi#1]
Google Colab でインストール時にエラーになりました。

```
!pip install -e . -v
    :
    creversi_cpp/creversi.h:58:8: error: ‘memcpy’ is not a member of ‘std’
```

gccでは以下のインクルードが必要なようです。

```
#include <cstring>
```

修正後、ブログのサンプルが動作することを確認しました。

https://colab.research.google.com/drive/1IzAXXxmBLFkOEaN4IEGH-kjHXLA7sUy3

**Comment by TadaoYamaoka** [comment]
修正しました。ありがとう！
