### ISSUE TITLE
コンパイルのやり方を教えてください

### ISSUE THREAD

**Issue by yutanakamur** [TadaoYamaoka/creversi#4]
やったこと
creversiをzip形式でダウンロードして、setup.pyと同じ階層で  **python setup.py build_ext --inplace** コマンドを入力した。

結果
**creversi_cpp/board.hpp:46:10: fatal error: 'byteswap.h' file not found** と出力されコンパイルされない。

なぜ
報酬関数を自分で定義したものにして使いたいと思いcreversi-masterをまずコンパイルしてみた。
そして、元のcreversiと同じようにAPIを使いたい。

**Comment by TadaoYamaoka** [comment]
インストール済みの場合は、pip uninstall creversiでアンインストールした後、
pip install -e .
でビルドして開発モードでインストールできます。
