### ISSUE TITLE
GSSから駒の動きを覚えさせる部分のプログラムについて

### ISSUE THREAD

**Issue by onozuka777** [TadaoYamaoka/creversi#5]
お世話になります。
強化学習を0から学ぶための材料として、オセロを選択し、このサイトにたどり着きました。
Yamaoka先生のブログ
https://tadaoyamaoka.hatenablog.com/entry/2019/11/30/162054
で、
GGSからダウンロードした棋譜をレーティング2000以上、手数45以上でフィルタリングして、9,831,855局面の学習データを作成した。
（処理に使用したコードはこちら）
https://github.com/TadaoYamaoka/creversi_gym/blob/master/creversi_gym/ggf_to_training_data.py
というプログラムがあるのですが、これをJupyter Notebookで実行したところ、

An exception has occurred, use %tb to see the full traceback.

SystemExit: 2

というエラーがでました。
①こちらのプログラムはJupyter notebook向きではないでしょうか。
②仕組みとして、このプログラムがGGSからどのように学習しているのか、コードから読み取れませんでした。
　実際にGGSのサイトに行って学習している部分というのが、すみません、分からず、教えていただけるでしょうか。

pandasなどで分析はそこそこやっているのですが、強化学習は複数のclassからオブジェクト指向で作成されていて
そこに苦手意識があり、初歩的な質問になってしまいすみません。
ご教示いただけますと幸いです。
何卒、よろしくお願い申し上げます。

**Comment by TadaoYamaoka** [comment]
特にJupyter notebookで動かなくなるような処理はないです。

ゼロから強化学習ということであれば、同人誌を販売していますので、

よろしければ参考にしてください。

https://booth.pm/ja/items/1830557
